version: "3.9"

services:
  api:
    build: .
    container_name: cats_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=super-secret-jwt
      - SQLALCHEMY_DATABASE_URI=sqlite:///data/database.db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
